apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-ishario
  namespace: tekton-demo
  annotations:
    tekton.dev/docker-0: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
stringData:
    username: ishario
    password: 'xxx'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: docker-hub-ishario
  namespace: tekton-demo
secrets:
- name: docker-hub-ishario
