apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci
  namespace: tekton-demo
spec:

  resources:
  - name: git-repo
    type: git
  - name: docker-image
    type: image
  params:
    - name: app-name
      type: string
    - name: git-message
      type: string

  tasks:

    - name: get-rc-version
      taskRef:
        name: get-rc-version
      params:
        - name: app-name
          value: $(params.app-name)
        - name: git-message
          value: $(params.git-message)
      resources:
        inputs:
          - name: git-repo
            resource: git-repo

    - name: build-rc-image
      taskRef:
        name: build-docker-image
      params:
        - name: rc-version
          value: $(tasks.get-rc-version.results.rc-version)
      resources:
        inputs:
          - name: git-repo
            resource: git-repo
        outputs:
          - name: docker-image
            resource: docker-image