apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: tekton-demo-app-ci
  namespace: tekton-demo
spec:
  params:
  params:
  - name: git-commit
  - name: git-url
  - name: git-message
  - name: docker-image
  - name: registry-sa
  - name: app-name

  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: app-ci-run-
    spec:
      serviceAccountName: $(params.registry-sa)
      pipelineRef:
        name: ci
      resources:
      - name: git-repo
        resourceSpec:
          type: git
          params:
          - name: revision
            value: $(params.git-commit)
          - name: url
            value: $(params.git-url)
      - name: docker-image
        resourceSpec:
          type: image
          params:
          - name: url
            value: $(params.docker-image)
      params:
      - name: app-name
        value: $(params.app-name)
      - name: git-message
        value: $(params.git-message)