apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: tekton-demo-app-ci
  namespace: tekton-demo
spec:
  params:
  params:
  - name: git-commit
  - name: git-url
  - name: git-message
  - name: docker-image
  - name: registry-sa
  - name: app-name

  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      generateName: get-rc-version-
    spec:
      taskref:
        name: get-rc-version
      resources:
      - name: git-repo
        resourceSpec:
          type: git
          params:
          - name: revision
            value: $(params.git-commit)
          - name: url
            value: $(params.git-url)
      params:
      - name: git-message
        value: $(params.git-message)

  - apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      generateName: build-docker-image-
    spec:
      serviceAccountName: $(params.registry-sa)
      taskref:
        name: build-docker-image
      resources:
      - name: git-repo
        resourceSpec:
          type: git
          params:
          - name: revision
            value: $(params.git-commit)
          - name: url
            value: $(params.git-url)
      - name: docker-image
        resourceSpec:
          type: image
          params:
          - name: url
            value: $(params.docker-image)
      params:
      - name: rc-version
        value: $(tasks.get-rc-version.results.rc-version)
