apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tekton-demo-app-ci
  namespace: tekton-demo
spec:
  params:
  - name: git-commit
    value: $(body.head_commit.id)
  - name: git-url
    value: $(body.repository.url)
  - name: git-message
    value: $(body.head_commit.message)
  - name: docker-image
    value: ishario/tektoncd-demo
  - name: registry-sa
    value: docker-hub-ishario
  - name: app-name
    value: 'tekton-demo'

