apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-docker-image
  namespace: tekton-demo
spec:
  params:
    - name: context
      type: string
  resources:
    inputs:
      - name: git-source
        type: git
    outputs:
      - name: docker-image
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.17.1
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(resources.inputs.git-source.path)/$(params.context)/Dockerfile
        - --destination=$(resources.outputs.docker-image.url)
        - --context=$(resources.inputs.git-source.path)/$(params.context)
