apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: docker-build-template
  namespace: tekton-demo
spec:
  params:
  - name: context
    default: /
  - name: git-branch
    default: master
  - name: git-repo-url
  - name: docker-image
  - name: docker-hub-sa

  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: docker-build-run-
    spec:
      serviceAccountName: $(params.docker-hub-sa)
      pipelineRef:
        name: build-image-from-git
      resources:
      - name: git-source
        resourceSpec:
          type: git
          params:
            - name: revision
              value: $(params.git-branch)
            - name: url
              value: $(params.git-repo-url)

      - name: docker-image
        resourceSpec:
          type: image
          params:
            - name: url
              value: $(params.docker-image)
      params:
      - name: context
        value: $(params.context)
