apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-image-from-git
  namespace: tekton-demo
spec:
  resources:
  - name: git-source
    type: git
  - name: docker-image
    type: image
  params:
    - name: context
      type: string

  tasks:
    - name: build-docker-image
      taskRef:
        name: build-docker-image
      params:
        - name: context
          value: "$(params.context)"
      resources:
        inputs:
          - name: git-source
            resource: git-source
        outputs:
          - name: docker-image
            resource: docker-image
