apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-rc-version
  namespace: tekton-demo
spec:
  params:
  - name: git-message
    type: string

  resources:
    inputs:
    - name: git-repo
      type: git

  results:
  - name: rc-version
    description: Candidate artefact version

  steps:
  - name: get-rc-version
    image: bash:latest
    script: |
      #!/usr/bin/env bash
      # Create RC version
      apk add git
      wget "https://raw.githubusercontent.com/ish-xyz/shell-semver/master/increment_version.sh"
      chmod +x increment_version.sh
      CURRENT_TAG=`cd $(resources.inputs.git-repo.path) && git tag -l | sort -V | tail -n1`
      [[ -z ${CURRENT_TAG} ]] && CURRENT_TAG=0.0.0
      if [[ "$(params.git-message)" =~ ^MAJOR: ]]; then
        CMD="-M"
      elif [[ "$(params.git-message)" =~ ^MINOR: ]]; then
        CMD="-m"
      else
        CMD="-p"
      fi

      echo -ne "rc-`bash ./increment_version.sh -p ${CURRENT_TAG}`" > /tekton/results/rc-version

