apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-docker-image
  namespace: tekton-demo
spec:
  params:
  - name: rc-version
    type: string

  resources:
    inputs:
    - name: git-repo
      type: git
    outputs:
    - name: docker-image
      type: image

  steps:
  - name: build-and-push
    image: git:latest
    env:
      - name: "DOCKER_CONFIG"
        value: "/tekton/home/.docker/"
    command:
      - /kaniko/executor
    args: [
      "--dockerfile=$(resources.inputs.git-repo.path)/src/Dockerfile",
      "--destination=$(resources.outputs.docker-image.url):$(params.rc-version)",
      "--context=$(resources.inputs.git-repo.path)/src",
    ]
