apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci
  namespace: tekton-demo
spec:
  resources:
  - name: git-app-source
    type: git
  - name: git-graph-files
    type: git
  - name: docker-app-image
    type: image
  params:
    - name: dockerfile-path
      type: string
    - name: app-name
      type: string

  tasks:
    - name: get-graph-file
      taskRef:
        name: get-graph-file
      params:
        - name: app-name
          value: "$(params.app-name)"
      resources:
        inputs:
          - name: git-graph-files
            resource: git-graph-files

    - name: build-candidate
      taskRef:
        name: build-candidate
      params:
        - name: dockerfile-path
          value: "$(params.dockerfile-path)"
      resources:
        inputs:
          - name: git-app-source
            resource: git-app-source
        outputs:
          - name: docker-app-image
            resource: docker-app-image
